### ISSUE TITLE
Morning session peer code review

### ISSUE THREAD

**Issue by ivangonzalez224** [Rysth/Awesome-Books#4]
Your project looks good 👍 
Keep the good work.

♻️  Changes required
Please try to use aria-label attribute when using inputs. aria-label attribute provides a text alternative for screen reader users to understand the purpose of the input element. 

https://github.com/Rysth/Awesome-Books/blob/912e242800574ae41ef57656ed46eca1c239fe4f/index.html#L42-L48

**Comment by Rysth** [comment]
Thanks @ivangonzalez224!

♻️ Changes Made

- ✅ Added `aria-label` to each input contained within the `form`.
